#############################################################################
# Makefile for building: TaskManager
# Generated by qmake (2.01a) (Qt 4.8.3) on: jeu. janv. 24 07:52:54 2013
# Project:  TaskManager.pro
# Template: subdirs
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile TaskManager.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-ihm \
		sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-Concept \
		sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-lib

src/ihm//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/ihm/ || $(MKDIR) src/ihm/ 
	cd src/ihm/ && $(QMAKE) /home/mael/Bureau/M1_ALMA/ihm/Project/src/ihm/ihm.pro -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o $(MAKEFILE)
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-ihm-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/ihm/ || $(MKDIR) src/ihm/ 
	cd src/ihm/ && $(QMAKE) /home/mael/Bureau/M1_ALMA/ihm/Project/src/ihm/ihm.pro -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o $(MAKEFILE)
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-ihm: src/ihm//$(MAKEFILE) FORCE
	cd src/ihm/ && $(MAKE) -f $(MAKEFILE)
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-ihm-make_default: src/ihm//$(MAKEFILE) FORCE
	cd src/ihm/ && $(MAKE) -f $(MAKEFILE) 
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-ihm-make_first: src/ihm//$(MAKEFILE) FORCE
	cd src/ihm/ && $(MAKE) -f $(MAKEFILE) first
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-ihm-all: src/ihm//$(MAKEFILE) FORCE
	cd src/ihm/ && $(MAKE) -f $(MAKEFILE) all
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-ihm-clean: src/ihm//$(MAKEFILE) FORCE
	cd src/ihm/ && $(MAKE) -f $(MAKEFILE) clean
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-ihm-distclean: src/ihm//$(MAKEFILE) FORCE
	cd src/ihm/ && $(MAKE) -f $(MAKEFILE) distclean
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-ihm-install_subtargets: src/ihm//$(MAKEFILE) FORCE
	cd src/ihm/ && $(MAKE) -f $(MAKEFILE) install
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-ihm-uninstall_subtargets: src/ihm//$(MAKEFILE) FORCE
	cd src/ihm/ && $(MAKE) -f $(MAKEFILE) uninstall
src/Concept//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/Concept/ || $(MKDIR) src/Concept/ 
	cd src/Concept/ && $(QMAKE) /home/mael/Bureau/M1_ALMA/ihm/Project/src/Concept/Concept.pro -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o $(MAKEFILE)
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-Concept-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/Concept/ || $(MKDIR) src/Concept/ 
	cd src/Concept/ && $(QMAKE) /home/mael/Bureau/M1_ALMA/ihm/Project/src/Concept/Concept.pro -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o $(MAKEFILE)
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-Concept: src/Concept//$(MAKEFILE) FORCE
	cd src/Concept/ && $(MAKE) -f $(MAKEFILE)
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-Concept-make_default: src/Concept//$(MAKEFILE) FORCE
	cd src/Concept/ && $(MAKE) -f $(MAKEFILE) 
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-Concept-make_first: src/Concept//$(MAKEFILE) FORCE
	cd src/Concept/ && $(MAKE) -f $(MAKEFILE) first
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-Concept-all: src/Concept//$(MAKEFILE) FORCE
	cd src/Concept/ && $(MAKE) -f $(MAKEFILE) all
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-Concept-clean: src/Concept//$(MAKEFILE) FORCE
	cd src/Concept/ && $(MAKE) -f $(MAKEFILE) clean
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-Concept-distclean: src/Concept//$(MAKEFILE) FORCE
	cd src/Concept/ && $(MAKE) -f $(MAKEFILE) distclean
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-Concept-install_subtargets: src/Concept//$(MAKEFILE) FORCE
	cd src/Concept/ && $(MAKE) -f $(MAKEFILE) install
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-Concept-uninstall_subtargets: src/Concept//$(MAKEFILE) FORCE
	cd src/Concept/ && $(MAKE) -f $(MAKEFILE) uninstall
src/lib//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/lib/ || $(MKDIR) src/lib/ 
	cd src/lib/ && $(QMAKE) /home/mael/Bureau/M1_ALMA/ihm/Project/src/lib/lib.pro -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o $(MAKEFILE)
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-lib-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/lib/ || $(MKDIR) src/lib/ 
	cd src/lib/ && $(QMAKE) /home/mael/Bureau/M1_ALMA/ihm/Project/src/lib/lib.pro -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o $(MAKEFILE)
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-lib: src/lib//$(MAKEFILE) FORCE
	cd src/lib/ && $(MAKE) -f $(MAKEFILE)
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-lib-make_default: src/lib//$(MAKEFILE) FORCE
	cd src/lib/ && $(MAKE) -f $(MAKEFILE) 
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-lib-make_first: src/lib//$(MAKEFILE) FORCE
	cd src/lib/ && $(MAKE) -f $(MAKEFILE) first
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-lib-all: src/lib//$(MAKEFILE) FORCE
	cd src/lib/ && $(MAKE) -f $(MAKEFILE) all
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-lib-clean: src/lib//$(MAKEFILE) FORCE
	cd src/lib/ && $(MAKE) -f $(MAKEFILE) clean
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-lib-distclean: src/lib//$(MAKEFILE) FORCE
	cd src/lib/ && $(MAKE) -f $(MAKEFILE) distclean
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-lib-install_subtargets: src/lib//$(MAKEFILE) FORCE
	cd src/lib/ && $(MAKE) -f $(MAKEFILE) install
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-lib-uninstall_subtargets: src/lib//$(MAKEFILE) FORCE
	cd src/lib/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: TaskManager.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile TaskManager.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/declarative_debug.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile TaskManager.pro

qmake_all: sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-ihm-qmake_all sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-Concept-qmake_all sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-lib-qmake_all FORCE

make_default: sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-ihm-make_default sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-Concept-make_default sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-lib-make_default FORCE
make_first: sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-ihm-make_first sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-Concept-make_first sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-lib-make_first FORCE
all: sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-ihm-all sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-Concept-all sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-lib-all FORCE
clean: sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-ihm-clean sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-Concept-clean sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-lib-clean FORCE
distclean: sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-ihm-distclean sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-Concept-distclean sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-lib-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-ihm-install_subtargets sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-Concept-install_subtargets sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-lib-install_subtargets FORCE
uninstall_subtargets: sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-ihm-uninstall_subtargets sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-Concept-uninstall_subtargets sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-lib-uninstall_subtargets FORCE

sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-ihm-check: src/ihm/$(MAKEFILE)
	cd src/ihm/ && $(MAKE) -f $(MAKEFILE) check
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-Concept-check: src/Concept/$(MAKEFILE)
	cd src/Concept/ && $(MAKE) -f $(MAKEFILE) check
sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-lib-check: src/lib/$(MAKEFILE)
	cd src/lib/ && $(MAKE) -f $(MAKEFILE) check
check: sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-ihm-check sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-Concept-check sub--home-mael-Bureau-M1_ALMA-ihm-Project-src-lib-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

